CREATE SEQUENCE SEQUENCIA_CODIGO_TAREFA START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE FUNCTION PROXIMO_CODIGO_TAREFA(PROXIMO_CODIGO OUT BIGINT) AS $$ BEGIN SELECT INTO PROXIMO_CODIGO NEXTVAL('SEQUENCIA_CODIGO_TAREFA')::BIGINT; END $$ LANGUAGE plpgsql VOLATILE;